backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  repo: ergoplatform/sigmaverse
  base_url: https://sigmaverse.io

publish_mode: editorial_workflow
media_folder: "static" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: 'new_project'
    label: 'Project'
    description: "All sigmaverse projects"
    folder: 'applications'
    path: '{{slug}}/overview'
    media_folder: '/'
    public_folder: '/'
    create: true
    identifier_field: name
    fields:
      - {
        label: "Name",
        name: "name",
        widget: "text"
      }
      - {
        label: "Description",
        name: "description",
        widget: "text"
      }
      - {
        label: "Website",
        name: "website",
        widget: "text"
      }
      - {
        label: "Logotype",
        name: "logo_image",
        widget: "image",
      }
      - {
        label: "Preview",
        name: "preview_image",
        widget: "image",
      }
      # - {
      #   label: "Category",
      #   name: "category",
      #   widget: "select",
      #   multiple: false,
      #   options: ["Design", "UX", "Dev"],
      #   default: ["Design"]
      # }

