backend:
  name: github
  branch: main # Branch to update (optional; defaults to master)
  repo: ergoplatform/sigmaverse
  base_url: https://sigmaverse.io

publish_mode: editorial_workflow
media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'en_blog'
    label: 'English blog post'
    folder: 'applications/'
    path: '{{slug}}/overview'
    media_folder: ''
    public_folder: ''
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
