on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main
jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy the app
        run: bash ./tools/deploy.sh

